name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: push
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.API_GITHUB }}
        src_path: /.
        src_branch: main
        dst_branch: master
        dst_path: /.
        dst_owner: EpitechPromo2025
        dst_repo_name: B-CPP-500-TLS-5-2-rtype-antoine.cadeau
        commit_message: "[CI] - Push to ID: ${{ github.run_id }} by github action from ${{ github.repository }}"