name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  test_server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install qt5
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: linux
        target: desktop
        arch: x86_64
        dir: /opt/qt
    - name: Install SFML
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update && sudo apt-get upgrade
        sudo apt-get install libsfml-dev
    - name: Build
      run: |
        cd server
        cmake -B build -S . -DCMAKE_PREFIX_PATH=/opt/qt/5.15.2/gcc_64/lib/cmake 
        cmake --build build -v
    - name: Run tests
      run: |
        cd server/bin
        ./R-Type_Server
  test_client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install qt5
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: linux
        target: desktop
        arch: x86_64
        dir: /opt/qt
    - name: Install SFML
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update && sudo apt-get upgrade
        sudo apt-get install libsfml-dev
    - name: Build
      run: |
        cd client
        cmake -B build -S . -DCMAKE_PREFIX_PATH=/opt/qt/5.15.2/gcc_64/lib/cmake
        cmake --build build -v
    - name: Run tests
      run: |
        cd client/bin
        ./R-Type_Client 127.0.0.1 4242
  push:
    runs-on: ubuntu-latest
    steps:
    - name: push
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.API_GITHUB }}
        src_path: /.
        src_branch: main
        dst_branch: main
        dst_path: /.
        dst_owner: EpitechPromo2025
        dst_repo_name: B-CPP-500-TLS-5-2-rtype-antoine.cadeau
        commit_message: "[CI] - Push to ID: ${{ github.run_id }} by github action from ${{ github.repository }}"